In [1]:
# if torch.Tensor's attribute of requires_grad=True, is tracks all operations on it, so you can call .backward()
# and automatically compute all gradients (these are accumulated in the .grad attribute)

In [2]:
import torch
torch.manual_seed(42)

In [3]:
# create tensor and start tracking computation
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [4]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [5]:
# y was created as a result of an operation, so it has a "gradient function"
print(y.grad_fn) # was created with addition 

In [6]:
z = y * y * 3 # created with multiplication
out = z.mean() # created with mean

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [7]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True) # Manually sets requires_grad to True, if this isn't true, b.grad_fn = None
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [8]:
out.backward() # Because out contains a single scalar, out.backward() is equivalent to out.backward(torch.tensor(1.))

In [9]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [10]:
x = torch.randn(3, requires_grad=True)
y = x * 2
while y.data.norm() < 1000:
    y = y * 2
print(y)

tensor([-574.9025,  -95.4001, 1130.5991], grad_fn=<MulBackward0>)


In [11]:
"""
in this case y is no longer a scalar. torch.autograd could not compute the full Jacobian directly,
but if we just want the vector-Jacobian product, simply pass the vector to backward as argument
"""
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


In [12]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [13]:
print(x.requires_grad)
y = x.detach() #removes variable from gradient tracking
print(y.requires_grad)
print(x.eq(y).all()) # Checking equality

True
False
tensor(True)
