In [1]:
from __future__ import print_function
import torch

In [2]:
# This creates an empty 5x3 matrix
ii = torch.empty(5, 3)
print(ii)

tensor([[9.9184e-39, 8.7245e-39, 9.2755e-39],
        [8.9082e-39, 9.9184e-39, 8.4490e-39],
        [9.6429e-39, 1.0653e-38, 1.0469e-38],
        [4.2246e-39, 1.0378e-38, 9.6429e-39],
        [9.2755e-39, 9.7346e-39, 1.0745e-38]])


In [3]:
print(torch.rand(5, 3))

tensor([[0.1788, 0.4100, 0.8646],
        [0.0195, 0.7073, 0.6307],
        [0.6373, 0.8279, 0.5543],
        [0.4957, 0.0156, 0.0980],
        [0.0397, 0.8539, 0.9226]])


In [5]:
# A torch long is equivalent to int64: https://pytorch.org/docs/stable/tensors.html
print(torch.zeros(5, 3, dtype=torch.long))

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
x = torch.tensor([5.5, 3, 2.90003444334321234])
print(x)

tensor([5.5000, 3.0000, 2.9000])


In [8]:
x.size()

torch.Size([3])

In [23]:
y = torch.rand(5,3)
print(x + y)

tensor([[5.6843, 3.6674, 3.4917],
        [5.8048, 3.0298, 3.1421],
        [5.8098, 3.0492, 3.2756],
        [6.1791, 3.5933, 3.5051],
        [5.9073, 3.1725, 3.6393]])


In [21]:
result = torch.empty(8, 8) # Empty torches get reshaped, apparently
torch.add(x, y, out=result) # Adding and sending to other tensor in the same line! 
print(result)

tensor([[6.3363, 3.0184, 3.8037],
        [6.0091, 3.4567, 3.4344],
        [6.3004, 3.8161, 3.4169],
        [6.2906, 3.2836, 3.2059],
        [5.6078, 3.9344, 3.7926]])


In [26]:
print(y)
y.add_(x)
print('-------')
print(y)

tensor([[5.6843, 3.6674, 3.4917],
        [5.8048, 3.0298, 3.1421],
        [5.8098, 3.0492, 3.2756],
        [6.1791, 3.5933, 3.5051],
        [5.9073, 3.1725, 3.6393]])
-------
tensor([[11.1843,  6.6674,  6.3917],
        [11.3048,  6.0298,  6.0422],
        [11.3098,  6.0492,  6.1756],
        [11.6791,  6.5933,  6.4051],
        [11.4073,  6.1725,  6.5393]])


In [27]:
# Use .item() to get a Python number of a single element tensor
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.6930])
-0.6929606199264526


In [36]:
# torches can be indexed as well, in [row][column] order
print(y[1][0].item())

11.304767608642578


In [38]:
print(y)
print('---------')
print(y.numpy())

tensor([[11.1843,  6.6674,  6.3917],
        [11.3048,  6.0298,  6.0422],
        [11.3098,  6.0492,  6.1756],
        [11.6791,  6.5933,  6.4051],
        [11.4073,  6.1725,  6.5393]])
---------
[[11.184345   6.6674194  6.391701 ]
 [11.304768   6.0298443  6.0421643]
 [11.309796   6.0491576  6.1755943]
 [11.679131   6.593277   6.405126 ]
 [11.407299   6.1724977  6.539294 ]]


In [39]:
import numpy as np
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [40]:
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
